#  __  __  ___  _   _ ___ _____ ___  ____  ____  
# |  \/  |/ _ \| \ | |_ _|_   _/ _ \|  _ \/ ___| 
# | |\/| | | | |  \| || |  | || | | | |_) \___ \ 
# | |  | | |_| | |\  || |  | || |_| |  _ < ___) |
# |_|  |_|\___/|_| \_|___| |_| \___/|_| \_\____/ 

# See https://wiki.hyprland.org/Configuring/Monitors/

#monitor=, preferred,auto,1

# Quand on ferme le capot (switch ON) -> couper l’écran du portable
bindl = , switch:on:Lid Switch, exec, hyprctl keyword monitor "eDP-1, disable"

# Quand on ouvre le capot (switch OFF) -> rallumer l’écran du portable
bindl = , switch:off:Lid Switch, exec, hyprctl keyword monitor ", preferred, auto, 1"

