#     _   _   _ _____ ___  ____ _____  _    ____ _____ 
#    / \ | | | |_   _/ _ \/ ___|_   _|/ \  |  _ \_   _|
#   / _ \| | | | | || | | \___ \ | | / _ \ | |_) || |  
#  / ___ \ |_| | | || |_| |___) || |/ ___ \|  _ < | |  
# /_/   \_\___/  |_| \___/|____/ |_/_/   \_\_| \_\|_| 

# Execute your favorite apps at launch
exec-once = waybar 
exec-once = hyprpaper
exec-once = mako
exec-once = bash "$HOME/.config/hypr/scripts/random_wallpaper.sh"
exec-once = [workspace 1 silent] brave
exec-once = [workspace 9 silent] discord --start-minimized